.release_rules:
  rules:
    - if: $RP_RELEASE_BRANCH == $CI_COMMIT_REF_NAME
      when: on_success
    - if: $RP_RELEASE_BRANCH == null && $CI_COMMIT_REF_NAME =~ /^hotfix\/.*$/
      when: on_success
    - if: $RP_RELEASE_BRANCH == null && $CI_COMMIT_REF_NAME =~ /^fix\/.*$/
      when: on_success
    - if: $RP_RELEASE_BRANCH == null && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_REF_NAME
      when: never

.non-release_rules:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix\/.*$/
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^fix\/.*$/
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: never
    - if: $RP_RELEASE_BRANCH == $CI_COMMIT_REF_NAME
      when: never
    - if: $CI_COMMIT_REF_NAME
