.release_rules:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix\/.*$/
    - if: $CI_COMMIT_REF_NAME =~ /^fix\/.*$/
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

.nonrelease_rules:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^hotfix\/.*$/
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^fix\/.*$/
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_REF_NAME
