.setup_base:
  image: python:3.10.4
  cache:
    paths:
      - .cache/pip
      - venv/
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install fire==0.3.1
    - pip install GitPython==3.1.27
    - pip install packaging==21.3
    - ./config.sh || true
