include:
  - local: core/build-alpha.yml
  - local: core/build-candidate.yml
  - local: core/build-debug.yml

.build_base:
  extends:
    - .base
  stage: build
  interruptible: true
  after_script: | 
    #### Preparing build env ####
    set -e
    
    if [[ "${_SEMVER}" !=  "${SEMVER}" ]]; then
        echo "⚠️ SEMVER was overridden! derived SEMVER: ${_SEMVER} passed SEMVER: ${SEMVER} ⚠️ "
        echo "⚠️ Setting _SEMVER to derived SEMVER.  SEMVER will remain as passed. ⚠️ "
        echo "_SEMVER=${_SEMVER}" >> ${CI_PROJECT_DIR}/rp.env
    fi
    
    echo "BUILD_JOB=${CI_JOB_NAME}" >> ${CI_PROJECT_DIR}/rp.env
    echo "PRE_RELEASE=${PRE_RELEASE}" >> ${CI_PROJECT_DIR}/rp.env
    echo "SEMVER=${SEMVER}" >> ${CI_PROJECT_DIR}/rp.env
    
    cat ${CI_PROJECT_DIR}/rp.env

.build:
  script:
    - 'echo "no build config defined Add .build to pipeline to define."'

.build:override:
  stage: build
