include:
  - local: core/build-alpha.yml
  - local: core/build-candidate.yml
  - local: core/build-debug.yml

.build_base:
  extends:
    - .base
  stage: build
  interruptible: true
  after_script: | 
    #### Preparing build env ####
    set -e
    
    echo "BUILD_JOB=$CI_JOB_NAME" >> $CI_PROJECT_DIR/rp.env
    echo "PRE_RELEASE=$_PRE_RELEASE" >> $CI_PROJECT_DIR/rp.env
    echo "SEMVER=$SEMVER" >> $CI_PROJECT_DIR/rp.env
    
    cat $CI_PROJECT_DIR/rp.env

.build:override:
  stage: build
