include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

container_scanning:
  variables:
    DOCKER_USER: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
    CS_SEVERITY_THRESHOLD: HIGH
    GIT_STRATEGY: fetch
    DOCKERFILE_PATH: $DIR/Dockerfile
  rules:
    - if: $CONTAINER_SCANNING_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME
      exists:
        - "$DIR/Dockerfile"
  dependencies:
    - build:alpha
    - build:candidate
